# Generated by Django 3.2 on 2022-02-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, db_index=True, verbose_name='комментарий'),
        ),
    ]
