# Generated by Django 3.2 on 2022-02-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_deliverylocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryLocation',
        ),
    ]
